name: Gitee Mirror Action

on:
  push:
    paths:
    - '.github/workflows/**'
    branches: [ master ]
  pull_request:
    paths:
    - '.github/workflows/**'
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/NewNanCity
        dst: gitee/NewNanCity
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: org
        timeout: 600
        debug: true
        force_update: true
        static_list: "NewNanCity-OfficialWebsite"
